### PR TITLE
Update IndicatorViewPager.js

### PR DESCRIPTION
**Pull request by RiatIO**
The previous PR wasn't working as expected - sorry for that. This one should remove the warning, properly.

### CODE REVIEW

**Comment by ZeerakHameem32** [comment]
Hi, i am installing the library from npm. But the warning method is still there although in the master branch the method has been updated to "shouldComponentUpdate".

**Comment by RiatIO** [comment]
@ZeerakHameem32  - Yeah, the update is not published to NPM package yet. Hopefully, @abbasmoosavi  can merge this PR (because the previous was bit wrong), and then publish it.

**Comment by abbasmoosavi** [comment]
> @ZeerakHameem32 - Yeah, the update is not published to NPM package yet. Hopefully, @abbasmoosavi can merge this PR (because the previous was bit wrong), and then publish it.

I updated npm, try again now

**Comment by RiatIO** [comment]
You need to merge my new pull request - I forgot to return boolean value (which shouldComponentUpdate requires). Thus, the modification will show a new warning @abbasmoosavi

**Comment by abbasmoosavi** [comment]
> You need to merge my new pull request - I forgot to return boolean value (which shouldComponentUpdate requires). Thus, the modification will show a new warning @abbasmoosavi

Ok, I did and published it to npm

**Pull request merged**
